### ISSUE TITLE
Does not compile with current QtCreator trunk (> 3.1)

### ISSUE THREAD

**Issue by jhunold** [mloskot/qt-creator-plugin-boostbuild#8]
Hi! 
It seems that the QtCreator plugin API is not stable, so this plugin stopped compiling a short time after you published it. Do you have any plans to revive it? If yes, the best solution would be to submit it to qt-project.org for integration into the main QtCreator tree. Else I fear that this will be broken again and again.
I hope I can offer some help if needed.

**Comment by mloskot** [comment]
Should be fixed now, addressed by #11 and #12
